# Generated by Django 3.1.2 on 2022-07-08 18:09

from django.db import migrations, models
import jinja2.exceptions


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0002_auto_20220708_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=jinja2.exceptions.TemplateRuntimeError, serialize=False)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('medal', models.CharField(blank=True, choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze')], max_length=13)),
            ],
        ),
    ]
